import { AssistantLane } from '../contracts/assistant';
import { ChatNluIntent, ChatNluMemoryScope } from '../contracts/chat';

export interface ChatNluIntentExample {
  text: string;
  intent: ChatNluIntent;
  confidence: number;
  secondaryIntents?: ChatNluIntent[];
  memoryScopes?: {
    capture?: ChatNluMemoryScope;
    query?: ChatNluMemoryScope;
  };
  recommendedLane?: AssistantLane;
}

export const NLU_SEMANTIC_MIN_TOKENS = 4;

export const NLU_STOPWORDS = new Set<string>([
  'a', 'an', 'the',
  'i', 'me', 'my', 'mine', 'you', 'your', 'yours', 'we', 'us', 'our', 'ours', 'he', 'she', 'it', 'they', 'them',
  'this', 'that', 'these', 'those',
  'can', 'could', 'will', 'would', 'should', 'do', 'does', 'did', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had',
  'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by', 'from', 'about', 'as', 'into', 'over',
]);

const ex = (
  intent: ChatNluIntent,
  recommendedLane: AssistantLane,
  texts: string[],
  extras: Partial<Omit<ChatNluIntentExample, 'text' | 'intent' | 'confidence' | 'recommendedLane'>> = {},
): ChatNluIntentExample[] =>
  texts.map((text) => ({
    text,
    intent,
    confidence: 0.72,
    recommendedLane,
    ...extras,
  }));

/**
 * Source of truth for dependency-free semantic-lite NLU matching.
 * Keep examples realistic, varied, and reviewable; tests use separate held-out
 * fixtures so this catalog measures generalization instead of memorization.
 */
export const CHAT_NLU_INTENT_EXAMPLES: ChatNluIntentExample[] = [
  ...ex('conversation', 'conversation', [
    'tell me a quick story about the project',
    'say hello and check in with me',
    'explain that in simple terms',
    'walk me through the idea casually',
    'what do you think about this approach',
    'help me brainstorm options',
    'make this easier to understand',
    'talk through the tradeoffs with me',
    'give me a plain language explanation',
    'summarize the conversation so far',
    'help me think this through',
    'answer this without using tools',
    'give me your opinion on the wording',
    'make a concise response',
    'respond conversationally',
  ]),
  ...ex('research', 'research', [
    'search for the latest pricing changes',
    'what is the newest information about redis',
    'find current sources about model routing',
    'look up recent news on this topic',
    'verify this claim with sources',
    'check official documentation for the latest rule',
    'find more sources for this research brief',
    'compare recent reports about this company',
    'any newer source about this release',
    'research the current state of browser automation',
    'fetch the official page and summarize it',
    'use web sources to answer this',
    'what changed this week in the API',
    'find published evidence for this statement',
    'give me a cited update',
  ], { secondaryIntents: ['tool_request'] }),
  ...ex('memory_capture', 'memory', [
    'remember my name is Alex',
    'save my preference for concise reports',
    'remember that I prefer direct answers',
    'keep this project goal in memory',
    'remember our mission is local first automation',
    'store that we are working on chat routing',
    'remember this in this chat only',
    'save this detail for later',
    'keep note that the client prefers citations',
    'remember my preferred stack is TypeScript',
    'log this as a project memory',
    'capture this as a mission note',
    'remember I like short implementation plans',
    'save the goal for this workspace',
    'remember the current design decision',
  ], { memoryScopes: { capture: 'session' } }),
  ...ex('memory_query', 'memory', [
    'what do you remember about me',
    'what did we discuss earlier in this chat',
    'recall the project goal',
    'what do you know about my preferences',
    'find memory about the mission',
    'show relevant remembered context',
    'what have I told you before',
    'search memory for chat routing',
    'do you remember the plan we made',
    'what is stored about this project',
    'bring back earlier notes from this session',
    'lookup operator memory about me',
    'retrieve mission notes',
    'what context did we save',
    'summarize stored memory for this task',
  ], { memoryScopes: { query: 'all' } }),
  ...ex('task_create', 'tasking', [
    'create a task to review the plan tomorrow',
    'remind me to check the build',
    'schedule a follow up for next week',
    'make a task from this discussion',
    'track this action item',
    'monitor this issue later',
    'add a reminder about the release',
    'queue a follow up task',
    'turn this into a todo',
    'create work item for the bug',
    'set a reminder for the meeting',
    'make a task named review docs',
    'follow up on the research tomorrow',
    'watch this and notify me',
    'create an action item from this',
  ]),
  ...ex('advisory', 'advisory', [
    'what should I focus on this week',
    'recommend the next step',
    'give me strategic advice',
    'prepare a short briefing',
    'what is the best path forward',
    'help me prioritize the work',
    'advise me on the tradeoff',
    'what should we do next',
    'give an operator status update',
    'identify blockers and next actions',
    'suggest a plan of attack',
    'recommend a release approach',
    'help me decide between options',
    'brief me on the current status',
    'turn this into guidance',
  ]),
  ...ex('code_help', 'conversation', [
    'help me write a TypeScript function',
    'explain this code pattern',
    'design an API endpoint',
    'refactor this component',
    'implement a helper for parsing dates',
    'show me how to structure this module',
    'review this code architecture',
    'write unit tests for this service',
    'explain how this repository works',
    'make this function cleaner',
    'help build this React component',
    'draft the database schema',
    'give me coding examples',
    'improve this implementation plan',
    'help me integrate this library',
  ]),
  ...ex('troubleshooting', 'conversation', [
    'debug this failing test',
    'fix this bug in the service',
    'why is this request throwing an exception',
    'the build failed with this error',
    'investigate the broken behavior',
    'help diagnose this stack trace',
    'the UI is not updating correctly',
    'find the cause of the crash',
    'this endpoint returns a 500 error',
    'repair the failing workflow',
    'why does this command time out',
    'trace the regression',
    'the app crashes after upload',
    'fix the TypeScript compile error',
    'what is causing this failure',
  ]),
  ...ex('edit_request', 'conversation', [
    'rewrite the selected paragraph',
    'improve this selected text',
    'shorten the highlighted section',
    'formalize this sentence',
    'revise the current selection',
    'make this text clearer',
    'edit this passage',
    'tighten the selected wording',
    'turn this into a polished paragraph',
    'make the selection more professional',
    'simplify this highlighted text',
    'rewrite this for a report',
    'improve the tone of this selection',
    'make this paragraph concise',
    'clean up this selected copy',
  ]),
  ...ex('tool_request', 'conversation', [
    'use the asana tool for this',
    'call the notion integration',
    'run the browser tool',
    'use jira to create an issue',
    'open this with the fetch tool',
    'call a tool to inspect this',
    'use slack for the update',
    'invoke the repository tool',
    'use the selected MCP server',
    'run the file reader tool',
    'call web extract on this page',
    'use the installed skill',
    'run the task tool',
    'trigger the integration for this',
    'use the connected plugin',
  ], { secondaryIntents: ['task_create'] }),
  ...ex('settings_control', 'conversation', [
    'disable memory for this chat',
    'turn on web search mode',
    'change the tool mode to manual',
    'set permission mode to ask every time',
    'turn off selected plugins',
    'enable plan mode',
    'switch web mode to browser',
    'change my chat settings',
    'disable automatic tools',
    'turn on safe tool mode',
    'set the model preference',
    'change the selected tools',
    'enable memory capture',
    'turn off web browsing',
    'update chat controls',
  ]),
  ...ex('clarification_needed', 'conversation', [
    'do the thing we discussed',
    'make it better somehow',
    'handle that for me',
    'continue with the other option',
    'fix it like before',
    'use the better one',
    'set it up the usual way',
    'finish the previous idea',
    'choose the right setting',
    'move forward with that',
    'apply the change',
    'make the proper update',
    'do the next part',
    'use that plan',
    'take care of this',
  ]),
  ...ex('unknown', 'conversation', [
    'unclassifiable placeholder request',
    'unsupported future intent sample',
    'schema fallback unknown turn',
    'unrecognized routing category',
    'unknown persisted frame display',
    'future client intent value',
    'legacy unknown message',
    'unhandled intent compatibility',
    'unsupported old metadata frame',
    'unknown routing normalization',
    'schema migration unknown intent',
    'display only unknown chip',
    'unmapped intent example',
    'unknown compatibility state',
    'fallback unknown label',
  ]),
  ...ex('conversation', 'conversation', [
    'summarize this conversation recap',
    'respond conversational way',
    'talk through approach casually',
  ]),
  ...ex('memory_query', 'memory', [
    'what remember about me context',
    'recall project goal memory',
    'retrieve mission notes memory',
  ], { memoryScopes: { query: 'all' } }),
  ...ex('task_create', 'tasking', [
    'remind check build later',
    'schedule follow up week task',
    'turn discussion todo item',
    'track action item later',
  ]),
  ...ex('advisory', 'advisory', [
    'recommend next step strategy',
    'give strategic advice options',
    'brief current status blockers',
    'help prioritize work focus',
    'identify blockers actions next',
  ]),
  ...ex('code_help', 'conversation', [
    'explain code pattern clearly',
    'design API endpoint structure',
    'refactor React component cleanly',
  ]),
  ...ex('troubleshooting', 'conversation', [
    'debug failing test now',
    'fix broken behavior issue',
    'diagnose stack trace error',
    'repair failing workflow run',
    'trace regression source',
  ]),
  ...ex('edit_request', 'conversation', [
    'rewrite selected paragraph clearly',
    'improve selected text wording',
    'shorten highlighted section copy',
    'formalize sentence selection',
    'clean selected copy tone',
  ]),
  ...ex('tool_request', 'conversation', [
    'use asana tool now',
    'call notion integration tool',
    'run browser tool now',
    'invoke repository tool now',
    'trigger installed skill tool',
  ]),
  ...ex('clarification_needed', 'conversation', [
    'do thing discussed earlier',
    'make better somehow please',
    'finish previous idea now',
    'use better option then',
    'take care of this request',
  ]),
  ...ex('unknown', 'conversation', [
    'unknown future category display',
    'unsupported intent sample display',
    'unrecognized routing category value',
    'schema fallback unknown state',
  ]),
];
