import { Injectable } from '@nestjs/common';
import {
  AppBuilderProject,
  AppSpecJson,
  ArchitecturePlan,
  FileGraph,
  FileTask,
  RawClawAppManifest,
} from '@rawclaw/shared';
import { ContextEngineService, FileGenerationContext } from './context-engine.service';

type GenerationInput = {
  project: AppBuilderProject;
  spec: AppSpecJson;
  architecture: ArchitecturePlan;
  fileGraph: FileGraph;
  manifest: RawClawAppManifest;
  targetedPaths?: string[] | null;
};

@Injectable()
export class CodeGenerationEngineService {
  constructor(private readonly contextEngine: ContextEngineService) {}

  generateFiles(input: GenerationInput): Record<string, string> {
    const targeted = input.targetedPaths?.length ? new Set(input.targetedPaths) : null;
    const result: Record<string, string> = {};
    const tasks = input.fileGraph.generationOrder
      .map((filePath) => input.fileGraph.files.find((task) => task.path === filePath))
      .filter((task): task is FileTask => Boolean(task));

    for (const task of tasks) {
      if (targeted && !targeted.has(task.path)) continue;
      result[task.path] = this.renderTask(task, input);
    }

    return result;
  }

  private renderTask(task: FileTask, input: GenerationInput): string {
    const context = this.contextEngine.build({
      task,
      project: input.project,
      spec: input.spec,
      architecture: input.architecture,
      fileGraph: input.fileGraph,
      manifest: input.manifest,
    });

    switch (task.path) {
      case 'README.md':
        return this.renderReadme(context);
      case 'package.json':
        return this.renderPackageJson(input.project);
      case 'tsconfig.json':
        return this.renderTsConfig();
      case 'vite.config.ts':
        return this.renderViteConfig();
      case 'index.html':
        return this.renderIndexHtml(input.project.name);
      case 'src/main.tsx':
        return this.renderMain();
      case 'src/styles.css':
        return this.renderStyles(input.spec.domain);
      case 'src/rawclaw-sdk.ts':
        return this.renderSdkFile(input.manifest);
      case 'src/App.test.tsx':
        return this.renderAppTest(input.project, input.spec);
      case 'src/rawclaw-contract.test.ts':
        return this.renderRawClawContractTest(input.manifest);
      case 'rawclaw.app.manifest.json':
        return JSON.stringify(input.manifest, null, 2);
      case 'src/components/Calculator.tsx':
        return this.renderCalculatorComponent();
      case 'src/components/PromptConsole.tsx':
        return this.renderPromptConsoleComponent();
      case 'src/components/KpiCard.tsx':
        return this.renderKpiCardComponent();
      case 'src/App.tsx':
        return this.renderAppShell(input.project, input.spec);
      default:
        return [
          `// Generated placeholder for ${task.path}`,
          `// Purpose: ${context.task.purpose}`,
          `// Domain: ${context.spec.domain}`,
          `// Depends on: ${context.dependencies.map((dependency) => dependency.path).join(', ') || 'none'}`,
          'export {};',
          '',
        ].join('\n');
    }
  }

  private renderReadme(context: FileGenerationContext): string {
    return `# ${context.project.name}

Generated by the RawClaw Level 3 App Builder pipeline.

## Summary
${context.spec.summary}

## Domain
- ${context.spec.domain}

## UI sections
${context.spec.uiSections.map((section) => `- ${section}`).join('\n')}

## Control actions
${context.spec.controlActions.map((action) => `- ${action}`).join('\n')}

## Runtime events
${context.spec.runtimeEvents.map((event) => `- ${event}`).join('\n')}

## Validation commands
${context.architecture.validationCommands.map((command) => `- ${command}`).join('\n')}

## Routes
${context.spec.routes.map((route) => `- ${route.path} (${route.label})`).join('\n')}
`;
  }

  private renderPackageJson(project: AppBuilderProject): string {
    return JSON.stringify(
      {
        name: project.slug,
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          test: 'vitest run --environment jsdom',
          typecheck: 'tsc --noEmit -p tsconfig.json',
        },
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0',
        },
        devDependencies: {
          typescript: '^5.9.3',
          vite: '^5.0.0',
          vitest: '^2.1.9',
          jsdom: '^26.1.0',
          '@testing-library/react': '^16.3.2',
          '@testing-library/jest-dom': '^6.9.1',
          '@types/react': '^18.3.5',
          '@types/react-dom': '^18.3.0',
        },
      },
      null,
      2,
    );
  }

  private renderTsConfig(): string {
    return JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          useDefineForClassFields: true,
          lib: ['DOM', 'DOM.Iterable', 'ES2020'],
          allowJs: false,
          skipLibCheck: true,
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          strict: true,
          forceConsistentCasingInFileNames: true,
          module: 'ESNext',
          moduleResolution: 'Node',
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          types: ['vite/client'],
        },
        include: ['src', 'vite.config.ts'],
      },
      null,
      2,
    );
  }

  private renderViteConfig(): string {
    return `import { defineConfig } from 'vite';\n\nexport default defineConfig({\n  server: {\n    host: '127.0.0.1',\n  },\n});\n`;
  }

  private renderIndexHtml(title: string): string {
    return `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${title}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`;
  }

  private renderMain(): string {
    return `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './styles.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);\n`;
  }

  private renderStyles(domain: AppSpecJson['domain']): string {
    const calculatorAccent = domain === 'calculator' ? '#0bd3ff' : '#98f47d';
    return `:root {\n  color-scheme: dark;\n  --bg: #060814;\n  --panel: rgba(12, 18, 28, 0.92);\n  --panel-border: rgba(255, 255, 255, 0.09);\n  --accent: ${calculatorAccent};\n  --muted: #9ba8c6;\n  --text: #f6f8ff;\n}\n\n* { box-sizing: border-box; }\nbody {\n  margin: 0;\n  min-height: 100vh;\n  font-family: 'Segoe UI', system-ui, sans-serif;\n  background:\n    radial-gradient(circle at top left, rgba(11, 211, 255, 0.16), transparent 30%),\n    radial-gradient(circle at top right, rgba(142, 255, 179, 0.12), transparent 22%),\n    linear-gradient(180deg, #05070f, #0a1120 40%, #060814);\n  color: var(--text);\n}\n\nbutton, input, textarea { font: inherit; }\n.app-shell {\n  min-height: 100vh;\n  padding: 2.5rem;\n  display: grid;\n  gap: 1.5rem;\n}\n\n.hero-panel,\n.workspace-panel,\n.metric-card,\n.console-panel,\n.history-panel,\n.keypad-panel {\n  border: 1px solid var(--panel-border);\n  background: var(--panel);\n  border-radius: 24px;\n  backdrop-filter: blur(12px);\n  box-shadow: 0 24px 80px rgba(0, 0, 0, 0.35);\n}\n\n.eyebrow {\n  text-transform: uppercase;\n  letter-spacing: 0.18em;\n  color: var(--muted);\n  font-size: 0.72rem;\n}\n\n.hero-panel { padding: 1.5rem 1.6rem; }\n.hero-panel h1 { margin: 0.25rem 0 0.5rem; font-size: clamp(2rem, 4vw, 3.5rem); }\n.hero-panel p { margin: 0; max-width: 65ch; color: var(--muted); line-height: 1.6; }\n.grid { display: grid; gap: 1rem; }\n.grid.two-up { grid-template-columns: minmax(0, 1.2fr) minmax(280px, 0.8fr); }\n@media (max-width: 980px) { .app-shell { padding: 1rem; } .grid.two-up { grid-template-columns: 1fr; } }\n.calculator-shell { display: grid; grid-template-columns: minmax(0, 1fr) minmax(260px, 0.72fr); gap: 1rem; }\n@media (max-width: 920px) { .calculator-shell { grid-template-columns: 1fr; } }\n.display-panel,\n.history-panel,\n.keypad-panel,\n.workspace-panel,\n.console-panel { padding: 1.25rem; }\n.display-value { font-size: clamp(2rem, 5vw, 3.6rem); font-weight: 700; text-align: right; word-break: break-all; }\n.display-expression { text-align: right; color: var(--muted); min-height: 1.5rem; }\n.keypad-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 0.75rem; }\n.key-btn {\n  border: 1px solid rgba(255,255,255,0.08);\n  background: rgba(255,255,255,0.04);\n  color: var(--text);\n  border-radius: 18px;\n  min-height: 64px;\n  cursor: pointer;\n  transition: transform 0.18s ease, border-color 0.18s ease, background 0.18s ease;\n}\n.key-btn:hover { transform: translateY(-1px); border-color: rgba(11,211,255,0.4); }\n.key-btn.accent { background: linear-gradient(180deg, rgba(11,211,255,0.2), rgba(11,211,255,0.08)); }\n.key-btn.primary { background: linear-gradient(180deg, rgba(11,211,255,0.32), rgba(11,211,255,0.14)); color: white; }\n.history-list,\n.console-list,\n.metric-grid,\n.gallery-grid,\n.action-row,\n.filter-row,\n.spec-list { display: grid; gap: 0.75rem; }\n.action-row,\n.filter-row { display: flex; flex-wrap: wrap; align-items: center; }\n.history-item,\n.console-item,\n.metric-card,\n.gallery-card,\n.spec-item { padding: 0.9rem 1rem; }\n.metric-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n.gallery-grid { grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); }\n.gallery-card {\n  border: 1px solid rgba(255,255,255,0.08);\n  border-radius: 18px;\n  background: rgba(255,255,255,0.04);\n  color: var(--text);\n  text-align: left;\n  cursor: pointer;\n}\n.gallery-card.active { border-color: rgba(152,244,125,0.65); background: rgba(152,244,125,0.09); }\n.image-preview {\n  min-height: 320px;\n  border-radius: 22px;\n  border: 1px solid rgba(255,255,255,0.08);\n  display: grid;\n  place-items: center;\n  overflow: hidden;\n  background: linear-gradient(135deg, rgba(11,211,255,0.16), rgba(152,244,125,0.1));\n}\n.mock-image {\n  width: min(78%, 420px);\n  aspect-ratio: 4 / 3;\n  border-radius: 18px;\n  display: grid;\n  place-items: center;\n  font-weight: 700;\n  color: white;\n  transition: transform 0.18s ease;\n}\n.uploaded-image {\n  width: min(86%, 520px);\n  max-height: 420px;\n  object-fit: contain;\n  border-radius: 18px;\n  transition: transform 0.18s ease;\n}\n.chip {\n  display: inline-flex;\n  align-items: center;\n  gap: 0.35rem;\n  padding: 0.32rem 0.55rem;\n  border-radius: 999px;\n  background: rgba(255,255,255,0.06);\n  color: var(--muted);\n  font-size: 0.78rem;\n}\ninput, select {\n  border: 1px solid rgba(255,255,255,0.1);\n  background: rgba(255,255,255,0.04);\n  color: var(--text);\n  border-radius: 14px;\n  padding: 0.65rem 0.75rem;\n}\n@media (max-width: 760px) { .metric-grid { grid-template-columns: 1fr; } }\n`;
  }

  private renderSdkFile(manifest: RawClawAppManifest): string {
    return `export const rawClawManifest = ${JSON.stringify(manifest, null, 2)} as const;\n\nexport function emitRawClawEvent(type: string, payload: Record<string, unknown>) {\n  window.dispatchEvent(new CustomEvent('rawclaw:event', {\n    detail: { type, payload, timestamp: new Date().toISOString() },\n  }));\n}\n\nexport async function sendRawClawCommand(command: string, payload?: Record<string, unknown>) {\n  const response = await fetch(rawClawManifest.controlEndpoints.commands, {\n    method: 'POST',\n    headers: { 'Content-Type': 'application/json' },\n    body: JSON.stringify({\n      id: crypto.randomUUID(),\n      appId: rawClawManifest.appId,\n      command,\n      payload: payload || null,\n      requestedAt: new Date().toISOString(),\n    }),\n  });\n  return response.json();\n}\n`;
  }

  private renderAppTest(project: AppBuilderProject, spec: AppSpecJson): string {
    const expectedTitle = JSON.stringify(project.name);
    const expectedText = JSON.stringify(this.isImageViewerSpec(spec) ? 'Upload images' : project.name);
    const workflowHint = JSON.stringify(spec.features[0] || spec.uiSections[0] || project.name);
    return `import '@testing-library/jest-dom/vitest';\nimport { render, screen } from '@testing-library/react';\nimport { describe, expect, it } from 'vitest';\nimport App from './App';\n\ndescribe('generated app shell', () => {\n  it('renders the requested app title', () => {\n    render(<App />);\n    expect(screen.getByText(${expectedTitle})).toBeInTheDocument();\n  });\n\n  it('renders the primary workflow surface', () => {\n    render(<App />);\n    expect(screen.getByText(${expectedText}, { exact: false })).toBeInTheDocument();\n  });\n\n  it('keeps the requested workflow visible to users', () => {\n    render(<App />);\n    const bodyText = document.body.textContent || '';\n    expect(bodyText.toLowerCase()).toContain(${workflowHint}.toLowerCase().split(' ')[0]);\n  });\n});\n`;
  }

  private renderRawClawContractTest(manifest: RawClawAppManifest): string {
    const capabilityCommands = JSON.stringify(manifest.capabilities.map((capability) => capability.command));
    return `import { describe, expect, it } from 'vitest';\nimport { rawClawManifest } from './rawclaw-sdk';\n\nconst expectedCommands = ${capabilityCommands} as string[];\n\ndescribe('RawClaw manifest contract', () => {\n  it('declares control endpoints and routes', () => {\n    expect(rawClawManifest.appId).toBeTruthy();\n    expect(rawClawManifest.controlEndpoints.commands).toBeTruthy();\n    expect(rawClawManifest.controlEndpoints.events).toBeTruthy();\n    expect(rawClawManifest.routes.length).toBeGreaterThan(0);\n  });\n\n  it('exposes every prompt-derived capability once', () => {\n    const commands = rawClawManifest.capabilities.map((capability) => capability.command);\n    expect(commands).toEqual(expect.arrayContaining(expectedCommands));\n    expect(new Set(commands).size).toBe(commands.length);\n  });\n\n  it('keeps capabilities executable through structured commands', () => {\n    for (const capability of rawClawManifest.capabilities) {\n      expect(capability.id).toMatch(/^[a-z][a-z0-9_]*$/);\n      expect(capability.command).toMatch(/^[a-z][a-z0-9_.]*$/);\n      expect(typeof capability.description).toBe('string');\n    }\n  });\n});\n`;
  }

  private renderAppShell(project: AppBuilderProject, spec: AppSpecJson): string {
    if (spec.domain === 'calculator') {
      return `import Calculator from './components/Calculator';\n\nexport default function App() {\n  return (\n    <main className="app-shell">\n      <section className="hero-panel">\n        <div className="eyebrow">RawClaw App Builder</div>\n        <h1>${project.name}</h1>\n        <p>${spec.summary}</p>\n      </section>\n      <Calculator />\n    </main>\n  );\n}\n`;
    }

    if (spec.domain === 'ai_console') {
      return `import PromptConsole from './components/PromptConsole';\n\nexport default function App() {\n  return (\n    <main className="app-shell">\n      <section className="hero-panel">\n        <div className="eyebrow">RawClaw AI Console</div>\n        <h1>${project.name}</h1>\n        <p>${spec.summary}</p>\n      </section>\n      <PromptConsole />\n    </main>\n  );\n}\n`;
    }

    if (this.isImageViewerSpec(spec)) {
      return this.renderImageViewerApp(project, spec);
    }

    return this.renderDataDrivenApp(project, spec);
  }

  private isImageViewerSpec(spec: AppSpecJson): boolean {
    const text = [
      spec.title,
      spec.summary,
      ...spec.features,
      ...spec.uiSections,
      ...spec.controlActions,
      ...spec.runtimeEvents,
    ].join(' ').toLowerCase();
    return /\bimage\b/.test(text) && /\b(viewer|viewing|gallery|zoom|rotate|metadata)\b/.test(text);
  }

  private renderDataDrivenApp(project: AppBuilderProject, spec: AppSpecJson): string {
    const title = JSON.stringify(project.name);
    const summary = JSON.stringify(spec.summary);
    const features = JSON.stringify(spec.features.length ? spec.features : ['Primary workflow']);
    const sections = JSON.stringify(spec.uiSections.length ? spec.uiSections : ['Main workspace']);
    const models = JSON.stringify(spec.dataModel);
    const actions = JSON.stringify(spec.controlActions);
    const events = JSON.stringify(spec.runtimeEvents);
    return `const appTitle = ${title};\nconst summary = ${summary};\nconst features = ${features} as string[];\nconst sections = ${sections} as string[];\nconst dataModel = ${models} as Array<{ id: string; label: string; fields: string[] }>;\nconst controlActions = ${actions} as string[];\nconst runtimeEvents = ${events} as string[];\n\nconst metrics = sections.slice(0, 3).map((section, index) => ({\n  label: section,\n  value: String(index === 0 ? features.length : index === 1 ? controlActions.length : runtimeEvents.length),\n  delta: index === 0 ? 'features' : index === 1 ? 'actions' : 'events',\n}));\n\nexport default function App() {\n  return (\n    <main className="app-shell">\n      <section className="hero-panel">\n        <div className="eyebrow">RawClaw Generated App</div>\n        <h1>{appTitle}</h1>\n        <p>{summary}</p>\n      </section>\n      <section className="grid metric-grid">\n        {metrics.map((metric) => (\n          <article className="metric-card" key={metric.label}>\n            <div className="eyebrow">{metric.label}</div>\n            <div style={{ fontSize: '2rem', fontWeight: 700, marginTop: '0.35rem' }}>{metric.value}</div>\n            <div style={{ color: 'var(--muted)', marginTop: '0.35rem' }}>{metric.delta}</div>\n          </article>\n        ))}\n      </section>\n      <section className="grid two-up">\n        <div className="workspace-panel">\n          <div className="eyebrow">Requested Views</div>\n          <h2>Workspace sections</h2>\n          <div className="spec-list">\n            {sections.map((section) => <div className="spec-item" key={section}>{section}</div>)}\n          </div>\n        </div>\n        <div className="workspace-panel">\n          <div className="eyebrow">Data Model</div>\n          <h2>Local mock entities</h2>\n          <div className="spec-list">\n            {dataModel.length ? dataModel.map((model) => (\n              <div className="spec-item" key={model.id}>\n                <strong>{model.label}</strong>\n                <div style={{ color: 'var(--muted)', marginTop: '0.35rem' }}>{model.fields.join(', ')}</div>\n              </div>\n            )) : features.map((feature) => <div className="spec-item" key={feature}>{feature}</div>)}\n          </div>\n        </div>\n      </section>\n      <section className="grid two-up">\n        <div className="workspace-panel">\n          <div className="eyebrow">RawClaw Actions</div>\n          <h2>Control surface</h2>\n          <div className="action-row">\n            {controlActions.map((action) => <span className="chip" key={action}>{action}</span>)}\n          </div>\n        </div>\n        <div className="workspace-panel">\n          <div className="eyebrow">Runtime Events</div>\n          <h2>Event stream</h2>\n          <div className="action-row">\n            {runtimeEvents.map((event) => <span className="chip" key={event}>{event}</span>)}\n          </div>\n        </div>\n      </section>\n    </main>\n  );\n}\n`;
  }

  private renderImageViewerApp(project: AppBuilderProject, spec: AppSpecJson): string {
    const title = JSON.stringify(project.name);
    const summary = JSON.stringify(spec.summary);
    const actions = JSON.stringify(spec.controlActions);
    const events = JSON.stringify(spec.runtimeEvents);
    const sections = JSON.stringify(spec.uiSections);
    return [
      "import { ChangeEvent, useMemo, useState } from 'react';",
      "import { emitRawClawEvent } from './rawclaw-sdk';",
      "",
      "type ImageStatus = 'pending' | 'approved' | 'rejected';",
      "type ImageItem = {",
      "  id: string;",
      "  title: string;",
      "  owner: string;",
      "  status: ImageStatus;",
      "  priority: 'low' | 'normal' | 'urgent';",
      "  submittedDate: string;",
      "  dimensions: string;",
      "  size: string;",
      "  tags: string[];",
      "  notes: string;",
      "  palette: string;",
      "  src?: string;",
      "};",
      "",
      "type HistoryEntry = { id: string; imageTitle: string; action: string; at: string };",
      "",
      `const appTitle = ${title};`,
      `const summary = ${summary};`,
      `const controlActions = ${actions} as string[];`,
      `const runtimeEvents = ${events} as string[];`,
      `const requestedSections = ${sections} as string[];`,
      "",
      "const initialImages: ImageItem[] = [",
      "  { id: 'img-001', title: 'Storefront hero refresh', owner: 'Mira', status: 'pending', priority: 'urgent', submittedDate: '2026-05-01', dimensions: '2400 x 1600', size: '3.4 MB', tags: ['campaign', 'hero'], notes: 'Needs approval before the Monday launch.', palette: 'linear-gradient(135deg, #0bd3ff, #7c3aed)' },",
      "  { id: 'img-002', title: 'Operations badge set', owner: 'Dev', status: 'pending', priority: 'normal', submittedDate: '2026-04-30', dimensions: '1800 x 1200', size: '1.8 MB', tags: ['icons', 'ops'], notes: 'Check contrast and crop before publishing.', palette: 'linear-gradient(135deg, #98f47d, #0ea5e9)' },",
      "  { id: 'img-003', title: 'Partner announcement card', owner: 'Leah', status: 'approved', priority: 'low', submittedDate: '2026-04-28', dimensions: '1600 x 900', size: '1.2 MB', tags: ['social', 'partner'], notes: 'Approved for scheduling.', palette: 'linear-gradient(135deg, #f97316, #22c55e)' },",
      "  { id: 'img-004', title: 'Rejected mobile crop', owner: 'Anik', status: 'rejected', priority: 'normal', submittedDate: '2026-04-27', dimensions: '1200 x 1600', size: '2.1 MB', tags: ['mobile', 'crop'], notes: 'Subject is clipped on narrow screens.', palette: 'linear-gradient(135deg, #ef4444, #f59e0b)' },",
      "];",
      "",
      "export default function App() {",
      "  const [images, setImages] = useState<ImageItem[]>(initialImages);",
      "  const [selectedId, setSelectedId] = useState(initialImages[0].id);",
      "  const [query, setQuery] = useState('');",
      "  const [statusFilter, setStatusFilter] = useState<'all' | ImageStatus>('all');",
      "  const [tagFilter, setTagFilter] = useState('all');",
      "  const [zoom, setZoom] = useState(100);",
      "  const [rotation, setRotation] = useState(0);",
      "  const [favorites, setFavorites] = useState<string[]>([]);",
      "  const [history, setHistory] = useState<HistoryEntry[]>([",
      "    { id: 'hist-1', imageTitle: 'Partner announcement card', action: 'approved', at: '2026-04-28 14:20' },",
      "    { id: 'hist-2', imageTitle: 'Rejected mobile crop', action: 'rejected', at: '2026-04-27 09:45' },",
      "  ]);",
      "",
      "  const allTags = useMemo(() => Array.from(new Set(images.flatMap((image) => image.tags))).sort(), [images]);",
      "  const selected = images.find((image) => image.id === selectedId) || images[0];",
      "  const filteredImages = images.filter((image) => {",
      "    const matchesQuery = image.title.toLowerCase().includes(query.toLowerCase());",
      "    const matchesStatus = statusFilter === 'all' || image.status === statusFilter;",
      "    const matchesTag = tagFilter === 'all' || image.tags.includes(tagFilter);",
      "    return matchesQuery && matchesStatus && matchesTag;",
      "  });",
      "",
      "  const recordHistory = (image: ImageItem, action: string) => {",
      "    setHistory((current) => [{ id: crypto.randomUUID(), imageTitle: image.title, action, at: new Date().toLocaleString() }, ...current].slice(0, 8));",
      "  };",
      "",
      "  const handleUpload = (event: ChangeEvent<HTMLInputElement>) => {",
      "    const files = Array.from(event.target.files || []).filter((file) => file.type.startsWith('image/'));",
      "    if (!files.length) return;",
      "    const uploaded = files.map((file, index): ImageItem => ({",
      "      id: crypto.randomUUID(),",
      "      title: file.name.replace(/\\.[^.]+$/, ''),",
      "      owner: 'Local upload',",
      "      status: 'pending',",
      "      priority: index === 0 ? 'urgent' : 'normal',",
      "      submittedDate: new Date().toISOString().slice(0, 10),",
      "      dimensions: 'local file',",
      "      size: `${Math.max(1, Math.round(file.size / 1024))} KB`,",
      "      tags: ['uploaded'],",
      "      notes: 'Uploaded locally for preview and review.',",
      "      palette: 'linear-gradient(135deg, #0bd3ff, #98f47d)',",
      "      src: URL.createObjectURL(file),",
      "    }));",
      "    setImages((current) => [...uploaded, ...current]);",
      "    setSelectedId(uploaded[0].id);",
      "    setStatusFilter('all');",
      "    setTagFilter('all');",
      "    setQuery('');",
      "    recordHistory(uploaded[0], 'uploaded');",
      "    emitRawClawEvent('image.uploaded', { count: uploaded.length, imageIds: uploaded.map((image) => image.id), titles: uploaded.map((image) => image.title) });",
      "    event.target.value = '';",
      "  };",
      "",
      "  const chooseImage = (image: ImageItem) => {",
      "    setSelectedId(image.id);",
      "    emitRawClawEvent('image.opened', { imageId: image.id, title: image.title });",
      "  };",
      "",
      "  const updateStatus = (status: ImageStatus) => {",
      "    setImages((current) => current.map((image) => image.id === selected.id ? { ...image, status } : image));",
      "    recordHistory(selected, status);",
      "    emitRawClawEvent(status === 'approved' ? 'image.approved' : 'image.rejected', { imageId: selected.id, title: selected.title });",
      "  };",
      "",
      "  const updateFilters = (next: { query?: string; status?: 'all' | ImageStatus; tag?: string }) => {",
      "    if (next.query !== undefined) setQuery(next.query);",
      "    if (next.status !== undefined) setStatusFilter(next.status);",
      "    if (next.tag !== undefined) setTagFilter(next.tag);",
      "    emitRawClawEvent('filters.changed', { query: next.query ?? query, status: next.status ?? statusFilter, tag: next.tag ?? tagFilter });",
      "  };",
      "",
      "  const changeZoom = (nextZoom: number) => {",
      "    const bounded = Math.min(180, Math.max(50, nextZoom));",
      "    setZoom(bounded);",
      "    emitRawClawEvent('zoom.changed', { imageId: selected.id, zoom: bounded });",
      "  };",
      "",
      "  const rotateImage = () => {",
      "    const nextRotation = (rotation + 90) % 360;",
      "    setRotation(nextRotation);",
      "    emitRawClawEvent('image.rotated', { imageId: selected.id, rotation: nextRotation });",
      "  };",
      "",
      "  const toggleFavorite = () => {",
      "    setFavorites((current) => current.includes(selected.id) ? current.filter((id) => id !== selected.id) : [...current, selected.id]);",
      "    emitRawClawEvent('favorite.changed', { imageId: selected.id });",
      "  };",
      "",
      "  return (",
      "    <main className=\"app-shell\">",
      "      <section className=\"hero-panel\">",
      "        <div className=\"eyebrow\">RawClaw Image Viewer</div>",
      "        <h1>{appTitle}</h1>",
      "        <p>{summary}</p>",
      "      </section>",
      "      <section className=\"workspace-panel\">",
      "        <div className=\"eyebrow\">Gallery Overview</div>",
      "        <div className=\"filter-row\" style={{ marginTop: '0.85rem' }}>",
      "          <label className=\"key-btn primary\" style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: 44, padding: '0 1rem' }}>",
      "            Upload images",
      "            <input aria-label=\"Upload images\" type=\"file\" accept=\"image/*\" multiple onChange={handleUpload} style={{ display: 'none' }} />",
      "          </label>",
      "          <input aria-label=\"Search by title\" value={query} onChange={(event) => updateFilters({ query: event.target.value })} placeholder=\"Search by title\" />",
      "          <select aria-label=\"Filter by status\" value={statusFilter} onChange={(event) => updateFilters({ status: event.target.value as 'all' | ImageStatus })}>",
      "            <option value=\"all\">All statuses</option>",
      "            <option value=\"pending\">Pending</option>",
      "            <option value=\"approved\">Approved</option>",
      "            <option value=\"rejected\">Rejected</option>",
      "          </select>",
      "          <select aria-label=\"Filter by tag\" value={tagFilter} onChange={(event) => updateFilters({ tag: event.target.value })}>",
      "            <option value=\"all\">All tags</option>",
      "            {allTags.map((tag) => <option key={tag} value={tag}>{tag}</option>)}",
      "          </select>",
      "        </div>",
      "        <div className=\"gallery-grid\" style={{ marginTop: '1rem' }}>",
      "          {filteredImages.map((image) => (",
      "            <button type=\"button\" className={image.id === selected.id ? 'gallery-card active' : 'gallery-card'} key={image.id} onClick={() => chooseImage(image)}>",
      "              {image.src ? <img src={image.src} alt=\"\" className=\"mock-image\" style={{ width: '100%', objectFit: 'cover', marginBottom: '0.75rem' }} /> : <div className=\"mock-image\" style={{ width: '100%', background: image.palette, marginBottom: '0.75rem' }}>{image.title.slice(0, 2).toUpperCase()}</div>}",
      "              <strong>{image.title}</strong>",
      "              <div style={{ color: 'var(--muted)', marginTop: '0.35rem' }}>{image.owner} / {image.status}</div>",
      "            </button>",
      "          ))}",
      "        </div>",
      "      </section>",
      "      <section className=\"grid two-up\">",
      "        <div className=\"workspace-panel\">",
      "          <div className=\"eyebrow\">Single Image Viewer</div>",
      "          <h2>{selected.title}</h2>",
      "          <div className=\"image-preview\">",
      "            {selected.src ? <img src={selected.src} alt={selected.title} className=\"uploaded-image\" style={{ transform: `scale(${zoom / 100}) rotate(${rotation}deg)` }} /> : <div className=\"mock-image\" style={{ background: selected.palette, transform: `scale(${zoom / 100}) rotate(${rotation}deg)` }}>{selected.title}</div>}",
      "          </div>",
      "          <div className=\"action-row\" style={{ marginTop: '1rem' }}>",
      "            <button type=\"button\" className=\"key-btn\" onClick={() => changeZoom(zoom - 10)}>Zoom out</button>",
      "            <button type=\"button\" className=\"key-btn\" onClick={() => changeZoom(zoom + 10)}>Zoom in</button>",
      "            <button type=\"button\" className=\"key-btn\" onClick={() => changeZoom(100)}>Fit image</button>",
      "            <button type=\"button\" className=\"key-btn\" onClick={rotateImage}>Rotate</button>",
      "            <button type=\"button\" className=\"key-btn\" onClick={toggleFavorite}>{favorites.includes(selected.id) ? 'Favorited' : 'Favorite'}</button>",
      "          </div>",
      "          <div className=\"action-row\" style={{ marginTop: '0.75rem' }}>",
      "            <button type=\"button\" className=\"key-btn primary\" onClick={() => updateStatus('approved')}>Approve image</button>",
      "            <button type=\"button\" className=\"key-btn accent\" onClick={() => updateStatus('rejected')}>Reject image</button>",
      "          </div>",
      "        </div>",
      "        <aside className=\"workspace-panel\">",
      "          <div className=\"eyebrow\">Metadata / Details</div>",
      "          <h2>{selected.owner}</h2>",
      "          <div className=\"spec-list\">",
      "            <div className=\"spec-item\"><strong>Status</strong><div>{selected.status}</div></div>",
      "            <div className=\"spec-item\"><strong>Priority</strong><div>{selected.priority}</div></div>",
      "            <div className=\"spec-item\"><strong>Submitted</strong><div>{selected.submittedDate}</div></div>",
      "            <div className=\"spec-item\"><strong>Dimensions</strong><div>{selected.dimensions}</div></div>",
      "            <div className=\"spec-item\"><strong>Size</strong><div>{selected.size}</div></div>",
      "            <div className=\"spec-item\"><strong>Notes</strong><div>{selected.notes}</div></div>",
      "          </div>",
      "          <div className=\"action-row\" style={{ marginTop: '1rem' }}>{selected.tags.map((tag) => <span className=\"chip\" key={tag}>{tag}</span>)}</div>",
      "        </aside>",
      "      </section>",
      "      <section className=\"grid two-up\">",
      "        <div className=\"workspace-panel\">",
      "          <div className=\"eyebrow\">Review History</div>",
      "          <div className=\"history-list\" style={{ marginTop: '0.9rem' }}>",
      "            {history.map((entry) => <div className=\"history-item\" key={entry.id}><strong>{entry.action}</strong><div style={{ color: 'var(--muted)' }}>{entry.imageTitle} / {entry.at}</div></div>)}",
      "          </div>",
      "        </div>",
      "        <div className=\"workspace-panel\">",
      "          <div className=\"eyebrow\">RawClaw Control</div>",
      "          <h2>Manifest capabilities</h2>",
      "          <div className=\"action-row\">{controlActions.map((action) => <span className=\"chip\" key={action}>{action}</span>)}</div>",
      "          <h2 style={{ marginTop: '1rem' }}>Events</h2>",
      "          <div className=\"action-row\">{runtimeEvents.map((event) => <span className=\"chip\" key={event}>{event}</span>)}</div>",
      "          <h2 style={{ marginTop: '1rem' }}>Requested views</h2>",
      "          <div className=\"action-row\">{requestedSections.map((section) => <span className=\"chip\" key={section}>{section}</span>)}</div>",
      "        </div>",
      "      </section>",
      "    </main>",
      "  );",
      "}",
      "",
    ].join('\n');
  }
  private renderCalculatorComponent(): string {
    return `import { useEffect, useMemo, useState } from 'react';\nimport { emitRawClawEvent } from '../rawclaw-sdk';\n\ntype HistoryEntry = { expression: string; result: string };\n\nconst KEYS = [\n  ['C', 'DEL', '%', '/'],\n  ['7', '8', '9', '*'],\n  ['4', '5', '6', '-'],\n  ['1', '2', '3', '+'],\n  ['0', '.', '='],\n];\n\nfunction safeEvaluate(expression: string): string {\n  if (!expression.trim()) return '0';\n  const normalized = expression.replace(/%/g, '/100');\n  try {\n    const result = Function('return (' + normalized + ')')();\n    if (typeof result !== 'number' || !Number.isFinite(result)) return 'Error';\n    return String(Number(result.toFixed(12)));\n  } catch {\n    return 'Error';\n  }\n}\n\nexport default function Calculator() {\n  const [expression, setExpression] = useState('');\n  const [result, setResult] = useState('0');\n  const [history, setHistory] = useState<HistoryEntry[]>([]);\n\n  const canEvaluate = useMemo(() => /\\d/.test(expression), [expression]);\n\n  const pushHistory = (nextExpression: string, nextResult: string) => {\n    setHistory((current) => [{ expression: nextExpression, result: nextResult }, ...current].slice(0, 8));\n  };\n\n  const emitState = (type: string, payload: Record<string, unknown>) => {\n    emitRawClawEvent(type, payload);\n  };\n\n  const handleDigit = (value: string) => {\n    setExpression((current) => {\n      const next = current + value;\n      emitState('expression.changed', { expression: next });\n      return next;\n    });\n  };\n\n  const handleAction = (value: string) => {\n    if (value === 'C') {\n      setExpression('');\n      setResult('0');\n      emitState('calculator.cleared', { expression: '', result: '0' });\n      return;\n    }\n    if (value === 'DEL') {\n      setExpression((current) => {\n        const next = current.slice(0, -1);\n        emitState('expression.changed', { expression: next });\n        return next;\n      });\n      return;\n    }\n    if (value === '=') {\n      if (!canEvaluate) return;\n      const nextResult = safeEvaluate(expression);\n      setResult(nextResult);\n      pushHistory(expression, nextResult);\n      emitState('result.calculated', { expression, result: nextResult });\n      return;\n    }\n    handleDigit(value);\n  };\n\n  useEffect(() => {\n    const onKeyDown = (event: KeyboardEvent) => {\n      if ((/^[0-9.]$/).test(event.key)) {\n        handleDigit(event.key);\n      } else if (['+', '-', '*', '/', '%'].includes(event.key)) {\n        handleDigit(event.key);\n      } else if (event.key === 'Enter') {\n        event.preventDefault();\n        handleAction('=');\n      } else if (event.key === 'Backspace') {\n        handleAction('DEL');\n      } else if (event.key.toLowerCase() === 'c') {\n        handleAction('C');\n      }\n    };\n    window.addEventListener('keydown', onKeyDown);\n    return () => window.removeEventListener('keydown', onKeyDown);\n  }, [expression, canEvaluate]);\n\n  return (\n    <section className="calculator-shell">\n      <div className="grid">\n        <div className="display-panel workspace-panel">\n          <div className="eyebrow">Expression</div>\n          <div className="display-expression">{expression || '0'}</div>\n          <div className="display-value">{result}</div>\n        </div>\n        <div className="keypad-panel">\n          <div className="eyebrow" style={{ marginBottom: '0.75rem' }}>Keypad</div>\n          <div className="keypad-grid">\n            {KEYS.flat().map((key) => (\n              <button\n                key={key}\n                type="button"\n                className={['key-btn', key === '=' ? 'primary' : ['+', '-', '*', '/', '%'].includes(key) ? 'accent' : ''].join(' ').trim()}\n                onClick={() => handleAction(key)}\n              >\n                {key}\n              </button>\n            ))}\n          </div>\n        </div>\n      </div>\n      <aside className="history-panel">\n        <div className="eyebrow">History</div>\n        <div className="history-list" style={{ marginTop: '0.9rem' }}>\n          {history.length ? history.map((entry) => (\n            <div key={entry.expression + entry.result} className="history-item">\n              <div style={{ color: 'var(--muted)' }}>{entry.expression}</div>\n              <div style={{ fontWeight: 700 }}>{entry.result}</div>\n            </div>\n          )) : <div style={{ color: 'var(--muted)' }}>Your latest calculations appear here.</div>}\n        </div>\n      </aside>\n    </section>\n  );\n}\n`;
  }

  private renderPromptConsoleComponent(): string {
    return `import { useState } from 'react';\n\ntype RunEntry = { prompt: string; status: string; summary: string };\n\nexport default function PromptConsole() {\n  const [prompt, setPrompt] = useState('Review this release plan and propose safer rollout steps.');\n  const [history, setHistory] = useState<RunEntry[]>([\n    { prompt: 'Summarize the last approval queue.', status: 'completed', summary: '3 approvals pending, 1 high priority.' },\n  ]);\n\n  const runPrompt = () => {\n    if (!prompt.trim()) return;\n    setHistory((current) => [{ prompt, status: 'completed', summary: 'Run executed locally inside the generated console scaffold.' }, ...current].slice(0, 6));\n  };\n\n  return (\n    <section className="grid two-up">\n      <div className="console-panel">\n        <div className="eyebrow">Prompt Composer</div>\n        <h2>Run AI tool actions</h2>\n        <textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} style={{ width: '100%', minHeight: 180, marginTop: '0.8rem', borderRadius: 18, padding: '1rem', background: 'rgba(255,255,255,0.04)', color: 'white', border: '1px solid rgba(255,255,255,0.08)' }} />\n        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '0.8rem' }}>\n          <button type="button" className="key-btn primary" onClick={runPrompt}>Run tool</button>\n        </div>\n      </div>\n      <div className="console-panel">\n        <div className="eyebrow">Recent Runs</div>\n        <div className="console-list" style={{ marginTop: '0.9rem' }}>\n          {history.map((entry) => (\n            <div key={entry.prompt} className="console-item">\n              <div style={{ fontWeight: 700 }}>{entry.status}</div>\n              <div style={{ color: 'var(--muted)', marginTop: '0.35rem' }}>{entry.prompt}</div>\n              <div style={{ marginTop: '0.35rem' }}>{entry.summary}</div>\n            </div>\n          ))}\n        </div>\n      </div>\n    </section>\n  );\n}\n`;
  }

  private renderKpiCardComponent(): string {
    return `type Props = { label: string; value: string; delta: string };\n\nexport default function KpiCard({ label, value, delta }: Props) {\n  return (\n    <article className="metric-card">\n      <div className="eyebrow">{label}</div>\n      <div style={{ fontSize: '2rem', fontWeight: 700, marginTop: '0.35rem' }}>{value}</div>\n      <div style={{ color: 'var(--muted)', marginTop: '0.35rem' }}>{delta}</div>\n    </article>\n  );\n}\n`;
  }
}
